apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: app
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: backend 